# Pandas - Merge & Group by
Answer the questions below.


*   a) What is the full name of the state with the highest "total" population in 2012?

*   b) If we only consider the "total" population, what is the state with the highest population per area (sq. mi) in 2012?

* c) which area did get a pick-up(pickup_borough) the most?

* d) what is the average fare in each pickup_borough area?

In [30]:
# Following are shell commands to download the data
!curl -O https://raw.githubusercontent.com/jakevdp/data-USstates/master/state-population.csv
!curl -O https://raw.githubusercontent.com/jakevdp/data-USstates/master/state-areas.csv
!curl -O https://raw.githubusercontent.com/jakevdp/data-USstates/master/state-abbrevs.csv

24358.72s - pydevd: Sending message related to process being replaced timed-out after 5 seconds

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 57935  100 57935    0     0   106k      0 --:--:-- --:--:-- --:--:--  107k

24364.48s - pydevd: Sending message related to process being replaced timed-out after 5 seconds

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   835  100   835    0     0   1652      0 --:--:-- --:--:-- --:--:--  1670

24370.15s - pydevd: Sending message related to process being replaced timed-out after 5 seconds

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   872  100   872    0     0   1981      0 --:--:-- --:--:-- --:--:--  2004

In [97]:
import pandas as pd
import seaborn as sns

###### a,b #######
pop = pd.read_csv('state-population.csv')
areas = pd.read_csv('state-areas.csv')
abbrevs = pd.read_csv('state-abbrevs.csv')
pd.set_option('display.max_columns', 74)
pd.set_option('display.width', 500)

print('Population')
print(pop.head())
print()
print('Area')
print(areas.head())
print()
print('Abbreviation')
print(abbrevs.head())

###### c,d #######
taxisDf = sns.load_dataset('taxis')

print('Information')
print(taxisDf.info())
print()
print('Taxis')
print(taxisDf.head(50))

Information
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6433 entries, 0 to 6432
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   pickup           6433 non-null   datetime64[ns]
 1   dropoff          6433 non-null   datetime64[ns]
 2   passengers       6433 non-null   int64
 3   distance         6433 non-null   float64
 4   fare             6433 non-null   float64
 5   tip              6433 non-null   float64
 6   tolls            6433 non-null   float64
 7   total            6433 non-null   float64
 8   color            6433 non-null   object
 9   payment          6389 non-null   object
 10  pickup_zone      6407 non-null   object
 11  dropoff_zone     6388 non-null   object
 12  pickup_borough   6407 non-null   object
 13  dropoff_borough  6388 non-null   object
dtypes: datetime64[ns](2), float64(5), int64(1), object(6)
memory usage: 703.7+ KB
None

Taxis
                pickup             dropoff  passengers  distance  fare    tip  tolls   total   color      payment                    pickup_zone                   dropoff_zone pickup_borough dropoff_borough
0  2019-03-23 20:21:09 2019-03-23 20:27:24           1      1.60   7.0   2.15   0.00   12.95  yellow  credit card                Lenox Hill West            UN/Turtle Bay South      Manhattan       Manhattan
1  2019-03-04 16:11:55 2019-03-04 16:19:00           1      0.79   5.0   0.00   0.00    9.30  yellow         cash          Upper West Side South          Upper West Side South      Manhattan       Manhattan
2  2019-03-27 17:53:01 2019-03-27 18:00:25           1      1.37   7.5   2.36   0.00   14.16  yellow  credit card                  Alphabet City                   West Village      Manhattan       Manhattan
3  2019-03-10 01:23:59 2019-03-10 01:49:51           1      7.70  27.0   6.15   0.00   36.95  yellow  credit card                      Hudson Sq                 Yorkville West      Manhattan       Manhattan
4  2019-03-30 13:27:42 2019-03-30 13:37:14           3      2.16   9.0   1.10   0.00   13.40  yellow  credit card                   Midtown East                 Yorkville West      Manhattan       Manhattan
5  2019-03-11 10:37:23 2019-03-11 10:47:31           1      0.49   7.5   2.16   0.00   12.96  yellow  credit card      Times Sq/Theatre District                   Midtown East      Manhattan       Manhattan
6  2019-03-26 21:07:31 2019-03-26 21:17:29           1      3.65  13.0   2.00   0.00   18.80  yellow  credit card              Battery Park City        Two Bridges/Seward Park      Manhattan       Manhattan
7  2019-03-22 12:47:13 2019-03-22 12:58:17           0      1.40   8.5   0.00   0.00   11.80  yellow          NaN                    Murray Hill                       Flatiron      Manhattan       Manhattan
8  2019-03-23 11:48:50 2019-03-23 12:06:14           1      3.63  15.0   1.00   0.00   19.30  yellow  credit card              East Harlem South                 Midtown Center      Manhattan       Manhattan
9  2019-03-08 16:18:37 2019-03-08 16:26:57           1      1.52   8.0   1.00   0.00   13.30  yellow  credit card            Lincoln Square East                   Central Park      Manhattan       Manhattan
10 2019-03-16 10:02:25 2019-03-16 10:22:29           1      3.90  17.0   0.00   0.00   17.80  yellow         cash              LaGuardia Airport                        Astoria         Queens          Queens
11 2019-03-20 19:39:42 2019-03-20 19:45:36           1      1.53   6.5   2.16   0.00   12.96  yellow  credit card          Upper West Side South               Manhattan Valley      Manhattan       Manhattan
12 2019-03-18 21:27:14 2019-03-18 21:34:16           1      1.05   6.5   1.00   0.00   11.30  yellow  credit card                    Murray Hill                 Midtown Center      Manhattan       Manhattan
13 2019-03-19 07:55:25 2019-03-19 08:09:17           1      1.75  10.5   0.00   0.00   13.80  yellow         cash            Lincoln Square West      Times Sq/Theatre District      Manhattan       Manhattan
14 2019-03-27 12:13:34 2019-03-27 12:25:48           0      2.90  11.5   0.00   0.00   14.80  yellow         cash       Financial District North        Two Bridges/Seward Park      Manhattan       Manhattan
15 2019-03-16 17:53:34 2019-03-16 18:13:57           3      2.09  13.5   0.00   0.00   16.80  yellow         cash          Upper West Side North                   Clinton East      Manhattan       Manhattan
16 2019-03-15 12:36:05 2019-03-15 12:54:28           1      2.12  13.0   0.00   0.00   16.30  yellow         cash                   East Chelsea  Meatpacking/West Village West      Manhattan       Manhattan
17 2019-03-23 20:50:49 2019-03-23 21:02:07           1      2.60  10.5   2.00   0.00   16.30  yellow  credit card                 Midtown Center              East Harlem South      Manhattan       Manhattan
18 2019-03-27 06:28:36 2019-03-27 06:38:10           1      2.18   9.5   1.92   0.00   14.72  yellow  credit card                       Gramercy                 Midtown Center      Manhattan       Manhattan
19 2019-03-25 22:04:25 2019-03-25 22:11:30           6      1.08   6.5   1.08   0.00   11.38  yellow  credit card                   East Chelsea                   East Chelsea      Manhattan       Manhattan
20 2019-03-21 03:37:34 2019-03-21 03:44:13           1      1.07   6.5   1.54   0.00   11.84  yellow  credit card   Penn Station/Madison Sq West                       Kips Bay      Manhattan       Manhattan
21 2019-03-25 23:05:54 2019-03-25 23:11:13           1      0.80   5.5   2.30   0.00   11.60  yellow  credit card   Penn Station/Madison Sq West                    Murray Hill      Manhattan       Manhattan
22 2019-03-28 17:20:54 2019-03-28 17:55:57           1      9.82  31.5   8.31   5.76   49.87  yellow  credit card              LaGuardia Airport  Sutton Place/Turtle Bay North         Queens       Manhattan
23 2019-03-04 12:15:39 2019-03-04 12:26:53           5      1.09   8.5   2.36   0.00   14.16  yellow  credit card  Sutton Place/Turtle Bay North                  Midtown North      Manhattan       Manhattan
24 2019-03-24 09:53:28 2019-03-24 10:01:22           5      2.89   9.5   3.84   0.00   16.64  yellow  credit card                Lenox Hill West                       Gramercy      Manhattan       Manhattan
25 2019-03-25 08:01:01 2019-03-25 08:13:27           1      1.90  10.0   3.00   0.00   16.30  yellow  credit card            Lincoln Square East                  Midtown South      Manhattan       Manhattan
26 2019-03-03 02:45:36 2019-03-03 03:02:14           1      3.35  13.5   0.00   0.00   17.30  yellow         cash      West Chelsea/Hudson Yards                        Seaport      Manhattan       Manhattan
27 2019-03-16 20:30:36 2019-03-16 20:46:22           1      2.60  12.5   3.26   0.00   19.56  yellow  credit card                   Clinton East                Lenox Hill West      Manhattan       Manhattan
28 2019-03-20 12:25:31 2019-03-20 12:45:02           1      4.71  17.5   0.00   0.00   18.30  yellow  credit card                   Clinton West              East Harlem North      Manhattan       Manhattan
29 2019-03-06 08:09:03 2019-03-06 08:27:11           1      0.92  12.0   0.00   0.00   15.30  yellow         cash            UN/Turtle Bay South               Garment District      Manhattan       Manhattan
30 2019-03-10 15:14:20 2019-03-10 15:20:17           1      1.84   7.0   2.06   0.00   12.36  yellow  credit card                Lenox Hill West              East Harlem South      Manhattan       Manhattan
31 2019-03-01 02:55:55 2019-03-01 02:57:59           3      0.74   4.0   0.00   0.00    7.80  yellow         cash                   Clinton East      West Chelsea/Hudson Yards      Manhattan       Manhattan
32 2019-03-17 19:24:50 2019-03-17 19:29:58           1      0.62   5.5   1.00   0.00    9.80  yellow  credit card                 Midtown Center  Sutton Place/Turtle Bay North      Manhattan       Manhattan
33 2019-03-20 22:29:32 2019-03-20 22:32:24           2      0.65   4.5   2.49   0.00   10.79  yellow  credit card                  Midtown South                 Midtown Center      Manhattan       Manhattan
34 2019-03-21 10:48:02 2019-03-21 10:57:45           2      0.87   7.5   2.16   0.00   12.96  yellow  credit card                  Midtown North                   Clinton West      Manhattan       Manhattan
35 2019-03-01 17:39:58 2019-03-01 18:04:46           1      3.06  17.0   4.26   0.00   25.56  yellow  credit card      West Chelsea/Hudson Yards                Lenox Hill East      Manhattan       Manhattan
36 2019-03-22 17:28:51 2019-03-22 17:33:51           1      1.10   5.5   0.00   0.00    9.80  yellow         cash               Garment District                       Flatiron      Manhattan       Manhattan
37 2019-03-21 18:41:58 2019-03-21 19:15:25           1      3.13  20.5   0.00   0.00   24.80  yellow         cash                Lenox Hill East               Garment District      Manhattan       Manhattan
38 2019-03-18 16:03:14 2019-03-18 16:10:36           2      1.13   6.5   2.16   0.00   12.96  yellow  credit card                       Gramercy                    Murray Hill      Manhattan       Manhattan
39 2019-03-25 22:50:56 2019-03-25 22:59:51           1      2.47  10.0   2.76   0.00   16.56  yellow  credit card               Garment District          Upper West Side South      Manhattan       Manhattan
40 2019-03-07 15:15:46 2019-03-07 15:50:14           1      7.51  27.0   6.06   0.00   36.36  yellow  credit card                       Flatiron                Carroll Gardens      Manhattan        Brooklyn
41 2019-03-24 18:42:56 2019-03-24 19:09:00           0      4.50  20.0   0.00   0.00   23.30  yellow         cash           TriBeCa/Civic Center                       Kips Bay      Manhattan       Manhattan
42 2019-03-30 23:59:14 2019-03-30 23:59:17           1      0.00  80.0  20.08   0.00  100.38  yellow  credit card                            NaN                            NaN            NaN             NaN
43 2019-03-27 19:39:16 2019-03-27 20:00:26           1      9.50  28.0   0.00   5.76   35.06  yellow         cash              LaGuardia Airport       Washington Heights South         Queens       Manhattan
44 2019-03-14 07:19:29 2019-03-14 07:45:51           1      9.37  29.5   1.00   0.00   33.80  yellow  credit card              East Harlem South              Battery Park City      Manhattan       Manhattan
45 2019-03-07 11:19:21 2019-03-07 11:39:09           1      0.80  12.5   3.15   0.00   18.95  yellow  credit card            Lincoln Square East                   Midtown East      Manhattan       Manhattan
46 2019-03-20 11:40:59 2019-03-20 12:06:41           2      4.70  20.0   0.00   0.00   23.30  yellow         cash      Times Sq/Theatre District              Battery Park City      Manhattan       Manhattan
47 2019-03-13 06:17:45 2019-03-13 06:21:54           2      1.15   5.5   2.64   0.00   11.44  yellow  credit card          Upper East Side North                Lenox Hill West      Manhattan       Manhattan
48 2019-03-07 16:49:01 2019-03-07 16:57:07           1      1.30   7.0   0.00   0.00   11.30  yellow         cash            Lincoln Square East      Times Sq/Theatre District      Manhattan       Manhattan
49 2019-03-04 21:35:00 2019-03-04 21:53:42           1      4.87  17.5   0.00   0.00   21.30  yellow         cash                   West Village          Upper West Side South      Manhattan       Manhattan

In [60]:
pop_2012 = pop[(pop['ages'] == 'total') & (pop['year'] == 2012)]

In [88]:
pop_abb = pd.merge(
  pop_2012, 
  abbrevs, 
  left_on='state/region', 
  right_on='abbreviation'
)
pop_abb.drop('abbreviation', axis=1, inplace=True)
pop_abb.drop('ages', axis=1, inplace=True)
pop_abb.drop('year', axis=1, inplace=True)
max_pop_index = pop_abb['population'].idxmax()
state_of_highest_pop = pop_abb.loc[max_pop_index]
print('The highest population in 2012')
print(state_of_highest_pop)

The highest population in 2012
state/region            CA
population      37999878.0
state           California
Name: 4, dtype: object

In [87]:
merge_all = pd.merge(pop_abb, areas, left_on='state', right_on='state')
merge_all['population per area'] = merge_all['area (sq. mi)'] / merge_all['population']
max_pop_per_area_index = merge_all['population per area'].idxmax()
state_of_highest_pop_per_area = merge_all.loc[max_pop_per_area_index]
print('The highest population per area in 2012')
print(state_of_highest_pop_per_area)

The highest population per area in 2012
state/region                 AK
population             730307.0
state                    Alaska
area (sq. mi)            656425
population per area    0.898834
Name: 1, dtype: object

In [102]:
taxisDf['pickup_borough'].mode()[0]
taxisDf.groupby('pickup_borough')['fare'].mean()

pickup_borough
Bronx        20.999091
Brooklyn     16.520836
Manhattan    11.152889
Queens       24.934642
Name: fare, dtype: float64